baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "百无聊赖"
theme = "yinwang"
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = false
#pygmentsStyle = "dracula"
#pygmentsOptions = ['linenos']
# 代码高亮/chroma，hugo默认自带（可选）

[params]
    author = "yobrave Lee"
    github = "chinanf-boy"
    # gitlab = "yobrave"
    googleAnalytics = "UA-128555056-1" # 谷歌统计gtag
    highlight = "atom-one-dark" # 默认样式 `github`
    langs = ["go"]
    # 默认加载 highlight.min.js，但 一些不支持的语言, 你自己添加,
    # 其实也可以使用hugo自带的语法高亮器设置，不过我有点懒
    # single = false # 单页面的Home 按钮去除
    # menus = true # 想加更多目录，具体请看常见问题中的更多配置
    backgroundColor = "#fbf6ec" # 加点黄黄的背景色
    githubRepo = "https://github.com/chennqqi/t5.gsymy.com"
    editBtn = true # 两个字段一起，才能搞好编辑按钮
    anchorLink = "?" # 瞄点链接
    copyCode = true # 代码复制按钮
    imageZoom = true # 图片点击 zoom 一下
    labels = true # 添加标签链接